/**
 * JPA entity for FIDO2-registered user devices used to enforce sole control.
 */

package di.swallet.wpb.domain

import jakarta.persistence.*
import java.time.LocalDateTime

/**
 * Physical device credential that unlocks wallet operations through WebAuthn authentication.
 */
@Entity
@Table(name = "user_devices")
class UserDevice(
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long? = null,

    @Column(nullable = false)
    val userId: String = "",

    @Column(nullable = false, unique = true)
    val credentialId: String = "", // Unique ID generated by the FIDO2 authenticator

    @Column(columnDefinition = "TEXT", nullable = false)
    val publicKeyBase64: String = "", // Device public key

    @Column(nullable = false)
    val userHandle: String = "", // For FIDO2 internal mapping

    @Column(nullable = false)
    var signatureCount: Long = 0, // Used to detect cloned devices

    @Column(nullable = false)
    val registeredAt: LocalDateTime = LocalDateTime.now()
)
