package di.swallet.wpb.domain

import jakarta.persistence.*
import java.time.LocalDateTime

/**
 * Entity representing a user's physical device authorized via FIDO2/WebAuthn.
 * This stores the 'Authentication Key' used to unlock the 'Identity Key' in the HSM.
 */
@Entity
@Table(name = "user_devices")
class UserDevice(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long? = null,

    @Column(nullable = false)
    val userId: String = "",

    @Column(nullable = false, unique = true)
    val credentialId: String = "", // Unique ID generated by the FIDO2 authenticator

    @Column(columnDefinition = "TEXT", nullable = false)
    val publicKeyBase64: String = "", // The device's public key

    @Column(nullable = false)
    var signatureCount: Long = 0, // Used to detect cloned devices

    @Column(nullable = false)
    val registeredAt: LocalDateTime = LocalDateTime.now()
)