services:
  db:
    image: postgres:15-alpine
    container_name: di-swallet-db
    environment:
      POSTGRES_USER: pedro
      POSTGRES_PASSWORD: tese2026
      POSTGRES_DB: diswallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: