package di.swallet.wpb.format.mdoc

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class MdocCrossInteropIndependentVerifierTest {
    private val binding = MdocTestSupport.holderBinding()
    private val stack = MdocTestSupport.stack(holderBindings = listOf(binding))
    private val codec = stack.codec
    private val independent = IndependentMdocVerifier()

    @Test
    fun `issuerSigned generated by runtime is verifiable by independent verifier`() {
        val issued = codec.encode(
            MdocCredentialDocument(
                docType = "eu.europa.ec.eudi.pid.1",
                namespace = "eu.europa.ec.eudi.pid.1",
                claims = mapOf(
                    "given_name" to "Alice",
                    "family_name" to "Doe",
                    "birth_date" to "1990-01-01",
                ),
            ),
            binding.deviceCoseKey,
        )

        assertTrue(independent.verifyIssuerAuth(issued), independent.debugIssuerAuth(issued))
        assertEquals(
            "Alice",
            independent.extractIssuerSignedClaim(
                rawIssuerSignedB64Url = issued,
                namespace = "eu.europa.ec.eudi.pid.1",
                claim = "given_name",
            ),
        )
    }

    @Test
    fun `deviceResponse generated by runtime is verifiable by independent verifier`() {
        val issued = codec.encode(
            MdocCredentialDocument(
                docType = "org.iso.18013.5.1.mDL",
                namespace = "org.iso.18013.5.1",
                claims = mapOf(
                    "given_name" to "Alice",
                    "family_name" to "Doe",
                    "driving_privileges" to listOf("B"),
                ),
            ),
            binding.deviceCoseKey,
        )
        val presented = codec.buildDeviceResponse(
            originalIssuedPayload = issued,
            docType = "org.iso.18013.5.1.mDL",
            namespaceClaims = mapOf(
                "org.iso.18013.5.1" to mapOf(
                    "given_name" to "Alice",
                    "driving_privileges" to listOf("B"),
                ),
            ),
            requestedClaims = listOf("given_name", "driving_privileges"),
            handover = MdocTestSupport.handover(),
            holderKeyAlias = binding.alias,
        )

        assertTrue(independent.verifyDeviceResponse(presented))
        assertEquals(
            "Alice",
            independent.extractPresentedClaim(
                rawDeviceResponseB64Url = presented,
                namespace = "org.iso.18013.5.1",
                claim = "given_name",
            ),
        )
    }
}
